module.exports = {
  attributes: [
    'ATK',
    'DEF',
    'HP',
    'ATK %',
    'DEF %',
    'HP %',
    'SPD',
    'CRIT',
    'CDMG',
    'ACC',
    'RES',
    'ASS',
  ],
  buffs: [
    'Accuracy',
    'Attack',
    'Barrier',
    'Cleanse',
    'Counter',
    'Critical',
    'Critical Damage',
    'Critical Resistance',
    'Defense',
    'DMG Reduction',
    'Dodge',
    'Emergency Device',
    'Extra Turn',
    'Immunity',
    'Invincibility',
    'Random',
    'Reflect',
    'Rejuvenation',
    'Resistance',
    'Safeguard',
    'Speed',
    'Stealth',
    'Unyielding',
  ],
  debuffs: [
    'Anti-Heal',
    'Attack',
    'Blind',
    'Buff Block',
    'Burn',
    'Corrosion',
    'Critical',
    'Critical Damage',
    'Defense',
    'Dispel',
    'Mark',
    'Paralyze',
    'Provoke',
    'Resistance',
    'Restricted',
    'Shock',
    'Silence',
    'Slow',
    'Status Accuracy',
    'Stun',
  ],
  elements: {
    MOLTEN: 'RED',
    CRYSTAL: 'GREEN',
    THUNDER: 'BLUE',
  },
  pity: {
    summonCost: 180,
    collabPity: 16200,
    normalPity: 36000,
  },
};
